### ISSUE TITLE
Calling a local variable outside the for loop

### ISSUE THREAD

**Issue by RojhatToptamus** [BrightID/BrightID-SmartContract#14]
In the BrightID.sol(Soulbound), there is a problem with the current code snippet.  It reverts with "Undeclared identifier" because the variable"i" is not accessible outside the loop.

https://github.com/BrightID/BrightID-SmartContract/blob/0d1cd502cadade5e0a4e5850475e1d3c3ee5ec3f/BrightID.sol#L72-L78

A potential solution that might fix the issue:

`history[addrs[addrs.length-1]] = address(0);`

**Comment by adamstallard** [comment]
Thank you!  I committed the change to the soulbound branch.
