### ISSUE TITLE
Allow old contexids to be reused

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-SmartContract#8]
Allow a previous address to be reused if the timestamp on the current verification is newer than the last one that included the previous address.  See https://github.com/BrightID/BrightID-Node/issues/112 for the reason to support this.

Maybe the easiest way to do this is to set verification timestamps in the history addresses to the newest timestamp instead of zero, then instead of having a "revoked" mapping that has every address that isn't in the first position, have an "active" mapping that is a boolean whether or or not the address is in the first position.

I also think that exposing two mappings such as
`mapping(address => bool) public isRevoked;` (or `mapping(address => bool) public active;` )
and `mapping(address => uint) override public verifications;`

is not as good of an experience for the user of the smart contract as having a single mapping `mapping(address => Verification)` to a struct that is of the form

```
struct Verification {
  uint timestamp;
  bool active;
}
```

**Comment by siftal** [comment]
It's done.
